name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        run: |
          docker buildx build --tag ${{ secrets.ECR_REPOSITORY_URI }}:latest --push .

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to ECS
        run: |
          ecs-deploy \
            --cluster ${{ secrets.ECS_CLUSTER }} \
            --service-name ${{ secrets.ECS_SERVICE_NAME }} \
            --image ${{ secrets.ECR_REPOSITORY_URI }}:latest \
            --timeout 300

      - name: Run integration tests
        run: |
          ./scripts/integration-tests.sh

      - name: Rollback on failure
        if: failure()
        run: |
          ecs-deploy \
            --cluster ${{ secrets.ECS_CLUSTER }} \
            --service-name ${{ secrets.ECS_SERVICE_NAME }} \
            --image ${{ secrets.ECR_REPOSITORY_URI }}:previous \
            --timeout 300
